name: reinvent-randomized
channels:
  - pytorch
  - defaults
  - rdkit
dependencies:
  - python=3.6
  - rdkit=2019.03.2.0
  - pytorch=1.0
  - cudatoolkit=9.0
  - tqdm=4.26
  - nose=1.3
  - tensorflow
  - scipy
  - matplotlib=3.0.3
  - pip
  - pip:
      - tensorboardX
      - imageio
      - requests
      - moviepy
      - torchvision
      - deepsmiles
